---
  - name: Starting the Docker registry
    docker:
      image: registry:2
      name: registry
      state: started
      restart_policy: always
      detach: true
      ports:
        - '4000:5000'
      env:
        REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
