---
- name: Start the graphana container
  docker:
    detach: True
    image: "grafana/grafana:3.1.0"
    name: "grafana"
    ports: 
      - "3000:3000"
    state: started
    env: 
      INFLUXDB_HOST: "{{ influx_ip }}"
      INFLUXDB_PORT: 8086
      INFLUXDB_NAME: cadvisor
      INFLUXDB_USER: root
      INFLUXDB_PASS: root

- name: Install httplib2
  pip: name=httplib2
     
- name: Add the influx data source
  uri:
    url: http://{{ influx_ip }}:3000/api/datasources
    user: admin
    password: admin
    force_basic_auth: yes
    body_format: json
    HEADER_Content-Type: application/json
    method: POST
    status_code: 200,500
    body: "{ \"name\": \"influx\", \"type\": \"influxdb\", \"url\": \"http://{{ influx_ip }}\", \"access\": \"proxy\", \"database\": \"cadvisor\", \"user\": \"root\", \"password\": \"root\\" }"
