- name: Configure rally
  hosts: util
  sudo: True
  vars:
    os_env:
      OS_PROJECT_DOMAIN_ID: default
      OS_PROJECT_DOMAIN_NAME: default
      OS_USER_DOMAIN_ID: Default
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_NAME: admin
      OS_PROJECT_DOMAIN_NAME: default
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: demo
      OS_AUTH_URL: "http://{{ vip }}:5000/v3"
      OS_IDENTITY_API_VERSION: 3
      OS_REGION_NAME: "RegionOne"
  roles:
    - rally
