---
- name: Start the cadvisor
  docker:
    detach: True
    image: "google/cadvisor:v0.23.2"
    command: "-storage_driver_db=cadvisor -storage_driver_host={{ influx_ip }}:8086 -storage_driver=influxdb" 
    name: "cadvisor"
    ports: 
      # don't bind to the host port 8080 since swift is using it by default
      - "8888:8080"
    state: started
    volumes: 
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

