---
- name: Copy rally scenarios
  copy: src={{ bench.location }} dest=/root/rally_home/ owner=655500

- name: debug
  debug: msg="rally task start {{ bench.location | basename }} --task-args '{{ bench.args }}'"

- name: Run rally benchmark
  docker_container:
    name: "{{ bench.location | to_uuid }}"
    image: rallyforge/rally
    state: started
    volumes:
      - /root/rally_home:/home/rally
    command: rally task start {{ bench.location | basename }} --task-args '{{ bench.args }}'
  register: docker_output

- debug: var=docker_output.ansible_facts.ansible_docker_container.Id

- name: Wait for the end of the test, this may take a while...
  command: "docker ps -q --filter id={{ docker_output.ansible_facts.ansible_docker_container.Id }}"
  register: finished
  until: finished.stdout == ""
  delay: 20
  retries: 10000

- name: List available rally reports
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task list --uuids-only
  register: list

# Download rally results only if there are some reports to get back

- name: Generating rally reports
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task report --tasks {{ list.stdout | replace('\n', ' ') }} --out report.html
  when: list.stdout != ""
