---
- include: "rally.yml"
  when: 
    - inventory_hostname in groups['disco/rally']
    - enable_rally

- include: "influx.yml"
  when:
    - inventory_hostname in groups['disco/influx']
    - enable_monitoring

- include: "logs.yml"

- include: "conf.yml"
