---
- name: Copy the scenarios
  copy: src={{ rally_scenarios_dir }} dest=/root/rally_home owner=655500

#- name: Generate a tag for the task
#  command: uuidgen
#  register: tag
#
- name: Run the scenario
  docker:
    image: rallyforge/rally
    state: started
    volumes:
    - /root/rally_home:/home/rally
    command: ./launch_scenarios.sh ./{{ rally_scenarios_list }} {{ rally_times }} {{ rally_concurrency }}

- name: Wait for the end of the test, this may take a while...
  command: docker ps 
  register: finished
  until: finished.stdout.find("rally") == -1
  delay: 20
  retries: 10000

- name: Generating reports
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task list --uuids-only
  register: list

- name: Generating reports
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task report --tasks {{ list.stdout | replace('\n', ' ') }} --out report.html

- name: Make a tar of the execution environment
  command: tar -czf /root/rally.tar.gz /root/rally_home

- name: Pull back execution environment
  fetch: src=/root/rally.tar.gz dest={{ backup_dir }}/{{ inventory_hostname }}-rally.tar.gz flat=yes
