---
- name: Start the influx container
  docker:
    detach: True
    image: "tutum/influxdb:0.9"
    name: "influx"
    ports: 
      - "8083:8083"
      - "8086:8086"
    state: started
    expose: 
      - "8090"
      - "8099
      "

- name: Waiting for the influx service to become available
  wait_for: 
    host: "{{ influx_ip }}"
    port: 8086
    state: started
    delay: 2
    timeout: 20

- name: Create the cadvisor database
  shell: "curl -s -G http://{{ influx_ip }}:8086/query --data-urlencode 'q=CREATE DATABASE cadvisor'"
  register: result
  until: result.stdout == '{"results":[{}]}'
  retries: 10
  delay: 2



