---
- name: Installing Docker (with a registry) and Kolla on the node
  hosts: hosts
  sudo: True
  vars:
    kolla_internal_vip_address: ${kolla_internal_vip_address}
  tasks:
    - name: Update cache
      apt: update_cache=yes

    - name: Installing dependencies
      apt: name={{ item }} state=present
      with_items:
        - python-pip
        - git
        - libffi-dev
        - libssl-dev
        - python-dev
        - curl
        #- linux-image-generic-lts-wily

    - name: Install Docker
      shell: which docker > /dev/null || curl -sSL https://get.docker.io | bash

    - name: Configure Docker
      command: mkdir -p /etc/systemd/system/docker.service.d

    - name: Mount /run
      command: mount --make-shared /run

    - name: Install docker-py
      pip: name=docker-py

    - name: Clone Kolla
      git: >
        repo=https://git.openstack.org/openstack/kolla
        version=stable/mitaka
        dest=kolla

    - name: Install Kolla
      command: python setup.py install
      args: 
        chdir: kolla/

    - name: Copy kolla/etc/kolla to /etc/kolla
      command: cp -r kolla/etc/kolla /etc/
  
    - name: Send /etc/kolla/globals.yml
      template: src=../templates/globals.yml.jinja2 dest=/etc/kolla/globals.yml
